#include <QObject>
#include <QMap>

QMap<QString, QMap<QString, QString>> loadDiskAttrs()
{
	QMap<QString, QMap<QString, QString>> allInfos;
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("02", QObject::tr("Throughput Performance"));
		temp.insert("03", QObject::tr("Spin-Up Time"));
		temp.insert("04", QObject::tr("Start/Stop Count"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("06", QObject::tr("Read Channel Margin"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("08", QObject::tr("Seek Time Performance"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0A", QObject::tr("Spin Retry Count"));
		temp.insert("0B", QObject::tr("Recalibration Retries"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("0D", QObject::tr("Soft Read Error Rate stab"));
		temp.insert("16", QObject::tr("Current Helium Level"));
		temp.insert("B8", QObject::tr("End-to-End Error"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("BC", QObject::tr("Command Timeout"));
		temp.insert("BD", QObject::tr("High Fly Writes"));
		temp.insert("BE", QObject::tr("Airflow Temperature"));
		temp.insert("BF", QObject::tr("G-Sense Error Rate"));
		temp.insert("C0", QObject::tr("Power-off Retract Count"));
		temp.insert("C1", QObject::tr("Load/Unload Cycle Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("Hardware ECC recovered"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("C7", QObject::tr("UltraDMA CRC Error Count"));
		temp.insert("C8", QObject::tr("Write Error Rate"));
		temp.insert("C9", QObject::tr("Soft Read Error Rate"));
		temp.insert("CA", QObject::tr("Data Address Mark Error"));
		temp.insert("CB", QObject::tr("Run Out Cancel"));
		temp.insert("CC", QObject::tr("Soft ECC Correction"));
		temp.insert("CD", QObject::tr("Thermal Asperity Rate"));
		temp.insert("CE", QObject::tr("Flying Height"));
		temp.insert("CF", QObject::tr("Spin High Current"));
		temp.insert("D0", QObject::tr("Spin Buzz"));
		temp.insert("D1", QObject::tr("Offline Seek Performance"));
		temp.insert("D3", QObject::tr("Vibration During Write"));
		temp.insert("D4", QObject::tr("Shock During Write"));
		temp.insert("DC", QObject::tr("Disk Shift"));
		temp.insert("DD", QObject::tr("G-Sense Error Rate"));
		temp.insert("DE", QObject::tr("Loaded Hours"));
		temp.insert("DF", QObject::tr("Load/Unload Retry Count"));
		temp.insert("E0", QObject::tr("Load Friction"));
		temp.insert("E1", QObject::tr("Load/Unload Cycle Count"));
		temp.insert("E2", QObject::tr("Load 'In'-time"));
		temp.insert("E3", QObject::tr("Torque Amplification Count"));
		temp.insert("E4", QObject::tr("Power-Off Retract Cycle"));
		temp.insert("E6", QObject::tr("GMR Head Amplitude"));
		temp.insert("E7", QObject::tr("Temperature"));
		temp.insert("F0", QObject::tr("Head Flying Hours"));
		temp.insert("FA", QObject::tr("Read Error Retry Rate"));
		temp.insert("FE", QObject::tr("Free Fall Protection"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		allInfos["Smart"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("02", QObject::tr("Throughput Performance"));
		temp.insert("03", QObject::tr("Spin-Up Time"));
		temp.insert("04", QObject::tr("Start/Stop Count"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("06", QObject::tr("Read Channel Margin"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("08", QObject::tr("Seek Time Performance"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0A", QObject::tr("Spin Retry Count"));
		temp.insert("0B", QObject::tr("Recalibration Retries"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("0D", QObject::tr("Soft Read Error Rate stab"));
		temp.insert("C0", QObject::tr("Unsafe Shutdown Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("FF", QObject::tr("Remaining Life"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		allInfos["SmartSsd"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("BB", QObject::tr("Total Erase Count"));
		allInfos["SmartMtron"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("B8", QObject::tr("Initial Bad Block Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("Program Failure Block Count"));
		temp.insert("C4", QObject::tr("Erase Failure Block Count"));
		temp.insert("C5", QObject::tr("Read Failure Block Count"));
		temp.insert("C6", QObject::tr("Total Count of Read Sectors"));
		temp.insert("C7", QObject::tr("Total Count of Write Sectors"));
		temp.insert("C8", QObject::tr("Total Count of Read Commands"));
		temp.insert("C9", QObject::tr("Total Count of Write Commands"));
		temp.insert("CA", QObject::tr("Total Count of Error bits from flash"));
		temp.insert("CB", QObject::tr("Total Count of Read Sectors with Correctable Bit Errors"));
		temp.insert("CC", QObject::tr("Bad Block Full Flag"));
		temp.insert("CD", QObject::tr("Maximum PE Count Specification"));
		temp.insert("CE", QObject::tr("Minimum Erase Count"));
		temp.insert("CF", QObject::tr("Maximum Erase Count"));
		temp.insert("D0", QObject::tr("Average Erase Count"));
		temp.insert("D1", QObject::tr("Remaining Drive Life"));
		allInfos["SmartIndilinx"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("E5", QObject::tr("Halt System ID, Flash ID"));
		temp.insert("E8", QObject::tr("Firmware Version Information"));
		temp.insert("E9", QObject::tr("ECC Fail Record"));
		temp.insert("EA", QObject::tr("Average Erase Count, Max Erase Count"));
		temp.insert("EB", QObject::tr("Good Block Count, System Block Count"));
		allInfos["SmartJMicron60x"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("03", QObject::tr("Spin Up Time"));
		temp.insert("04", QObject::tr("Start/Stop Count"));
		temp.insert("05", QObject::tr("Re-Allocated Sector Count"));
		temp.insert("09", QObject::tr("Power-On Hours Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Available Reserved Space"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss"));
		temp.insert("AF", QObject::tr("Power Loss Protection Failure"));
		temp.insert("B7", QObject::tr("SATA Downshift Count"));
		temp.insert("B8", QObject::tr("End to End Error Detection Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BE", QObject::tr("Temperature"));
		temp.insert("C0", QObject::tr("Unsafe Shutdown Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C5", QObject::tr("Pending Sector Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("E1", QObject::tr("Host Writes"));
		temp.insert("E2", QObject::tr("Timed Workload Media Wear"));
		temp.insert("E3", QObject::tr("Timed Workload Host Read/Write Ratio"));
		temp.insert("E4", QObject::tr("Timed Workload Timer"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("E9", QObject::tr("Media Wearout Indicator"));
		temp.insert("EA", QObject::tr("Thermal Throttle Status"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("F3", QObject::tr("Total NAND Writes"));
		temp.insert("F9", QObject::tr("Total NAND Writes"));
		allInfos["SmartIntel"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Reallocated Sector Count"));
		temp.insert("09", QObject::tr("Power-on Hours"));
		temp.insert("0C", QObject::tr("Power-on Count"));
		temp.insert("AF", QObject::tr("Program Fail Count (Chip)"));
		temp.insert("B0", QObject::tr("Erase Fail Count (Chip)"));
		temp.insert("B1", QObject::tr("Wear Leveling Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count (Chip)"));
		temp.insert("B3", QObject::tr("Used Reserved Block Count (Total)"));
		temp.insert("B4", QObject::tr("Unused Reserved Block Count (Total)"));
		temp.insert("B5", QObject::tr("Program Fail Count (Total)"));
		temp.insert("B6", QObject::tr("Erase Fail Count (Total)"));
		temp.insert("B7", QObject::tr("Runtime Bad Block (Total)"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BE", QObject::tr("Airflow Temperature"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("ECC Error Rate"));
		temp.insert("C6", QObject::tr("Off-Line Uncorrectable Error Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("C9", QObject::tr("Super cap Status"));
		temp.insert("CA", QObject::tr("SSD Mode Status"));
		temp.insert("EB", QObject::tr("POR Recovery Count"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("AA", QObject::tr("Unused Reserved Block Count (Chip) "));
		temp.insert("AB", QObject::tr("Program Fail Count (Chip)"));
		temp.insert("AC", QObject::tr("Erase Fail Count (Chip)"));
		temp.insert("AD", QObject::tr("Wear Leveling Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B8", QObject::tr("Error Detection"));
		temp.insert("E9", QObject::tr("Normalized Media Wear-out"));
		allInfos["SmartSamsung"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Retired Block Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("0D", QObject::tr("Soft Read Error Rate"));
		temp.insert("64", QObject::tr("Gigabytes Erased"));
		temp.insert("AA", QObject::tr("Reserve Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B1", QObject::tr("Wear Range Delta"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Fail Count"));
		temp.insert("B8", QObject::tr("Reported I/O Error Detection Code Errors"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("On-the-Fly ECC Uncorrectable Error Count"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("C7", QObject::tr("SATA R-Errors Error Count"));
		temp.insert("C9", QObject::tr("Uncorrectable Soft Read Error Rate"));
		temp.insert("CC", QObject::tr("Soft ECC Correction Rate"));
		temp.insert("E6", QObject::tr("Drive Life Protection Status"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("EB", QObject::tr("Power Fail Backup Health"));
		temp.insert("F1", QObject::tr("Lifetime Writes from Host"));
		temp.insert("F2", QObject::tr("Lifetime Reads from Host"));
		allInfos["SmartSandForce"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("02", QObject::tr("Throughput Performance"));
		temp.insert("03", QObject::tr("Spin-Up Time"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("08", QObject::tr("Seek Time Performance"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0A", QObject::tr("Spin Retry Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AF", QObject::tr("Bad Cluster Table Count (ECC Fail Count)"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		allInfos["SmartJMicron61x"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated NAND Blocks"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("0D", QObject::tr("Soft Error Rate"));
		temp.insert("0E", QObject::tr("Device Capacity (NAND)"));
		temp.insert("0F", QObject::tr("User Capacity"));
		temp.insert("10", QObject::tr("Spare Blocks Available"));
		temp.insert("11", QObject::tr("Remaining Spare Blocks"));
		temp.insert("64", QObject::tr("Total Erase Count"));
		temp.insert("AA", QObject::tr("Reserved Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average Block-Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B4", QObject::tr("Unused Reserve NAND Blocks"));
		temp.insert("B5", QObject::tr("Unaligned Access Count"));
		temp.insert("B7", QObject::tr("SATA Interface Downshift"));
		temp.insert("B8", QObject::tr("Error Correction Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("BC", QObject::tr("Command Timeout Count"));
		temp.insert("BD", QObject::tr("Factory Bad Block Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("Cumulative ECC Bit Correction Count"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C6", QObject::tr("Smart Off-line Scan Uncorrectable Error Count"));
		temp.insert("C7", QObject::tr("Ultra DMA CRC Error Rate"));
		temp.insert("CA", QObject::tr("Percent Lifetime Used"));
		temp.insert("CE", QObject::tr("Write Error Rate"));
		temp.insert("D2", QObject::tr("Successful RAIN Recovery Count"));
		temp.insert("EA", QObject::tr("Total Bytes Read"));
		temp.insert("F2", QObject::tr("Write Protect Progress"));
		temp.insert("F3", QObject::tr("ECC Bits Corrected"));
		temp.insert("F4", QObject::tr("ECC Cumulative Threshold Events"));
		temp.insert("F5", QObject::tr("Cumulative Program NAND Pages"));
		temp.insert("F6", QObject::tr("Total Host Sector Writes"));
		temp.insert("F7", QObject::tr("Host Program Page Count"));
		temp.insert("F8", QObject::tr("Background Program Page Count"));
		temp.insert("F9", QObject::tr("Total Refresh ISP Count"));
		temp.insert("FA", QObject::tr("Total Do RefCal Count"));
		temp.insert("FB", QObject::tr("Total NAND Read Plane Count (Low 4Bytes)"));
		temp.insert("FC", QObject::tr("Total NAND Read Plane Count (High 4Bytes)"));
		temp.insert("FD", QObject::tr("Total Block ReMap Pass Count"));
		temp.insert("FE", QObject::tr("Total Background Scan Over Limit Count"));
		temp.insert("DF", QObject::tr("Total Background Scan"));
		allInfos["SmartMicron"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("0D", QObject::tr("Soft Error Rate"));
		temp.insert("0E", QObject::tr("Device Capacity (NAND)"));
		temp.insert("0F", QObject::tr("User Capacity"));
		temp.insert("10", QObject::tr("Spare Blocks Available"));
		temp.insert("11", QObject::tr("Remaining Spare Blocks"));
		temp.insert("64", QObject::tr("Total Erase Count"));
		temp.insert("AA", QObject::tr("Reserved Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average Block-Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B4", QObject::tr("Unused Reserve NAND Blocks"));
		temp.insert("B7", QObject::tr("SATA Interface Downshift"));
		temp.insert("B8", QObject::tr("Error Correction Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("BC", QObject::tr("Command Timeout Count"));
		temp.insert("BD", QObject::tr("Factory Bad Block Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("Cumulative ECC Bit Correction Count"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C6", QObject::tr("Smart Off-line Scan Uncorrectable Error Count"));
		temp.insert("C7", QObject::tr("Ultra DMA CRC Error Rate"));
		temp.insert("CA", QObject::tr("Percent Lifetime Used"));
		temp.insert("CE", QObject::tr("Write Error Rate"));
		temp.insert("D2", QObject::tr("Successful RAIN Recovery Count"));
		temp.insert("EA", QObject::tr("Total Bytes Read"));
		temp.insert("F3", QObject::tr("ECC Bits Corrected"));
		temp.insert("F4", QObject::tr("ECC Cumulative Threshold Events"));
		temp.insert("F5", QObject::tr("Cumulative Program NAND Pages"));
		temp.insert("F6", QObject::tr("Total Host Sector Writes"));
		temp.insert("F7", QObject::tr("Host Program Page Count"));
		temp.insert("F8", QObject::tr("Background Program Page Count"));
		temp.insert("A0", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("A1", QObject::tr("Valid Spare Blocks"));
		temp.insert("A3", QObject::tr("Initial Invalid Blocks"));
		temp.insert("94", QObject::tr("Total SLC Erase Count"));
		temp.insert("95", QObject::tr("Maximum SLC Erase Count"));
		temp.insert("96", QObject::tr("Minimum SLC Erase Count"));
		temp.insert("97", QObject::tr("Average SLC Erase Count"));
		temp.insert("A4", QObject::tr("Total NAND Erase Count"));
		temp.insert("A5", QObject::tr("Maximum NAND Erase Count"));
		temp.insert("A6", QObject::tr("Minimum NAND Erase Count"));
		temp.insert("A7", QObject::tr("Average NAND Erase Count"));
		temp.insert("A9", QObject::tr("Percentage Lifetime Remaining"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Fail Count"));
		temp.insert("C0", QObject::tr("Power-off Retract Count"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("F1", QObject::tr("Total LBA Write"));
		temp.insert("F2", QObject::tr("Total LBA Read"));
		temp.insert("F5", QObject::tr("Total NAND Write Count"));
		temp.insert("F6", QObject::tr("Total SLC Write Count"));
		temp.insert("F7", QObject::tr("RAID Recovery Count"));
		temp.insert("F9", QObject::tr("Total Refresh ISP Count"));
		temp.insert("FA", QObject::tr("Total Do RefCal Count"));
		temp.insert("FB", QObject::tr("Total NAND Read Plane Count (Low 4Bytes)"));
		temp.insert("FC", QObject::tr("Total NAND Read Plane Count (High 4Bytes)"));
		temp.insert("FD", QObject::tr("Total Block ReMap Pass Count"));
		temp.insert("FE", QObject::tr("Total Background Scan Over Limit Count"));
		temp.insert("DF", QObject::tr("Total Background Scan"));
		allInfos["SmartMicronMU02"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("03", QObject::tr("Spin Up Time"));
		temp.insert("04", QObject::tr("Start Stop Count"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("E8", QObject::tr("Total Count of Write Sectors"));
		temp.insert("E9", QObject::tr("Remaining Life"));
		temp.insert("64", QObject::tr("Total Blocks Erased"));
		temp.insert("A7", QObject::tr("SSD Protect Mode"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("A9", QObject::tr("Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("B8", QObject::tr("Factory Bad Block Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("CA", QObject::tr("Total Number of Corrected Bits"));
		temp.insert("CD", QObject::tr("Max Rated PE Counts"));
		temp.insert("CE", QObject::tr("Minimum Erase Counts"));
		temp.insert("CF", QObject::tr("Maximum Erase Counts"));
		temp.insert("D3", QObject::tr("SATA Uncorrectable Error Count"));
		temp.insert("D4", QObject::tr("NAND Page Reads During Retry"));
		temp.insert("D5", QObject::tr("Simple Read Retry Attempts"));
		temp.insert("D6", QObject::tr("Adaptive Read Retry Attempts"));
		temp.insert("DD", QObject::tr("Internal Data Path Uncorrectable Errors"));
		temp.insert("DE", QObject::tr("RAID Recovery Count"));
		temp.insert("E6", QObject::tr("Power Loss Protection"));
		temp.insert("FB", QObject::tr("NAND Read Count"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		allInfos["SmartOcz"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Grown Bad Blocks"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average Program/Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("AF", QObject::tr("Program Fail Count (Worst Case)"));
		temp.insert("B0", QObject::tr("Erase Fail Count (Worst Case)"));
		temp.insert("B1", QObject::tr("Wear Leveling Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count (Worst Case)"));
		temp.insert("B3", QObject::tr("Used Reserved Block Count"));
		temp.insert("B4", QObject::tr("UnUsed Reserved Block Count (Total)"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Fail Count"));
		temp.insert("B7", QObject::tr("SATA Interface Down Shift"));
		temp.insert("B8", QObject::tr("End-to-End Data Errors Corrected"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BC", QObject::tr("Command Time out"));
		temp.insert("C0", QObject::tr("Unsafe Shutdown Count"));
		temp.insert("C3", QObject::tr("ECC rate"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("C7", QObject::tr("Ultra CRC Error Count"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("E9", QObject::tr("NAND GB written"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		allInfos["SmartPlextor"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Reserve Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average Write/Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("E6", QObject::tr("Percent of Total Write/Erase Count"));
		temp.insert("E8", QObject::tr("Spare Blocks Remaining"));
		temp.insert("EA", QObject::tr("Percent of Total Write/Erase Count (BC blocks)"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		allInfos["SmartSanDisk"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Accumulated Runtime Bad Blocks"));
		temp.insert("09", QObject::tr("Power-On Hours Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AB", QObject::tr("Available Over-Provisioned Block Count"));
		temp.insert("AE", QObject::tr("Power Cycle Count (Unplanned)"));
		temp.insert("BB", QObject::tr("Total Uncorrectable NAND Reads"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("Total Programming Failures"));
		temp.insert("C4", QObject::tr("Total Erase Failures"));
		temp.insert("C5", QObject::tr("Total Read Failures (Uncorrectable)"));
		temp.insert("C6", QObject::tr("Host Reads"));
		temp.insert("C7", QObject::tr("Host Writes"));
		temp.insert("D0", QObject::tr("Average Erase Count"));
		temp.insert("D2", QObject::tr("SATA CRC Error Count"));
		temp.insert("E9", QObject::tr("Remaining Life"));
		temp.insert("F9", QObject::tr("Total NAND Programming Count"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		temp.insert("64", QObject::tr("Total Blocks Erased"));
		temp.insert("B8", QObject::tr("Factory Bad Block Count Total"));
		temp.insert("CA", QObject::tr("Total Number Of Read Bits Corrected"));
		temp.insert("CD", QObject::tr("Max Rated PE Count"));
		temp.insert("CE", QObject::tr("Min Erase Count"));
		temp.insert("CF", QObject::tr("Max Erase Count"));
		temp.insert("D4", QObject::tr("Total Count NAND Pages Reads Requiring Read Retry"));
		temp.insert("D5", QObject::tr("Total Count of Simple Read Retry Attempts"));
		temp.insert("D6", QObject::tr("Total Count of Adaptive Read Retry Attempts"));
		temp.insert("DD", QObject::tr("Internal Data Path Protection Uncorrectable Errors"));
		temp.insert("DE", QObject::tr("RAID Recovery Count"));
		temp.insert("E0", QObject::tr("In Warranty"));
		temp.insert("E1", QObject::tr("DAS Polarity"));
		temp.insert("E2", QObject::tr("Partial Pfail"));
		temp.insert("E6", QObject::tr("Write Throttling Activation Flag"));
		temp.insert("F9", QObject::tr("Total NAND Programming Count (pages)"));
		temp.insert("FB", QObject::tr("Total NAND Read Count"));
		allInfos["SmartOczVector"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Retired Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Reserve Block Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("F1", QObject::tr("Lifetime GB Written"));
		temp.insert("F2", QObject::tr("Lifetime GB Read"));
		allInfos["SmartCorsair"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("02", QObject::tr("Throughput Performance"));
		temp.insert("03", QObject::tr("Spin-Up Time"));
		temp.insert("04", QObject::tr("Start/Stop Count"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("08", QObject::tr("Seek Time Performance"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0A", QObject::tr("Spin Retry Count"));
		temp.insert("0B", QObject::tr("Recalibration Retries"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A7", QObject::tr("SSD Protect Mode"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("A9", QObject::tr("Total Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("F1", QObject::tr("Total Host Writes"));
		temp.insert("F2", QObject::tr("Total Host Reads"));
		allInfos["SmartToshiba"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A5", QObject::tr("Block Erase Count (SLC)"));
		temp.insert("A6", QObject::tr("Minimum P/E Cycles"));
		temp.insert("A7", QObject::tr("Maximum Bad Blocks per die"));
		temp.insert("A8", QObject::tr("Maximum P/E Cycles"));
		temp.insert("A9", QObject::tr("Total Bad Block"));
		temp.insert("AA", QObject::tr("Grown Bad Blocks"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average P/E Cycles"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B8", QObject::tr("End-to-End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("BC", QObject::tr("Command Timeout Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("D4", QObject::tr("SATA PHY Error"));
		temp.insert("E6", QObject::tr("Media Wearout Indicator"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E8", QObject::tr("Available Reserve Space"));
		temp.insert("E9", QObject::tr("NAND GB Written"));
		temp.insert("EA", QObject::tr("NAND GB Written (SLC)"));
		temp.insert("EE", QObject::tr("Media Wearout Indicator (Cycles Remaining)"));
		temp.insert("F1", QObject::tr("Total GB Written"));
		temp.insert("F2", QObject::tr("Total GB Read"));
		temp.insert("F4", QObject::tr("Temperature Throttle Status"));
		temp.insert("F9", QObject::tr("NAND GB Written"));
		allInfos["SmartSanDiskGb"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("02", QObject::tr("Throughput Performance"));
		temp.insert("03", QObject::tr("Spin Up Time"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("08", QObject::tr("Seek Time Performance"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0A", QObject::tr("Spin Retry Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase count"));
		temp.insert("AF", QObject::tr("Bad Cluster Table Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Errors"));
		temp.insert("C0", QObject::tr("Unsafe Shutdown Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Later Bad Block Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("DA", QObject::tr("CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E9", QObject::tr("Lifetime Writes to Flash"));
		temp.insert("F0", QObject::tr("Write Head"));
		temp.insert("F1", QObject::tr("Host Writes"));
		temp.insert("F2", QObject::tr("Host Reads"));
		temp.insert("F4", QObject::tr("Average Erase Count"));
		temp.insert("F5", QObject::tr("Max Erase Count"));
		temp.insert("F6", QObject::tr("Total Erase Count"));
		allInfos["SmartKingston"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Critical Warning"));
		temp.insert("02", QObject::tr("Composite Temperature"));
		temp.insert("03", QObject::tr("Available Spare"));
		temp.insert("04", QObject::tr("Available Spare Threshold"));
		temp.insert("05", QObject::tr("Percentage Used"));
		temp.insert("06", QObject::tr("Data Units Read"));
		temp.insert("07", QObject::tr("Data Units Written"));
		temp.insert("08", QObject::tr("Host Read Commands"));
		temp.insert("09", QObject::tr("Host Write Commands"));
		temp.insert("0A", QObject::tr("Controller Busy Time"));
		temp.insert("0B", QObject::tr("Power Cycles"));
		temp.insert("0C", QObject::tr("Power On Hours"));
		temp.insert("0D", QObject::tr("Unsafe Shutdowns"));
		temp.insert("0E", QObject::tr("Media and Data Integrity Errors"));
		temp.insert("0F", QObject::tr("Number of Error Information Log Entries"));
		allInfos["SmartNVMe"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw data error rate"));
		temp.insert("05", QObject::tr("Reallocated sector count"));
		temp.insert("09", QObject::tr("Power on hour count"));
		temp.insert("0C", QObject::tr("Power cycle count"));
		temp.insert("A1", QObject::tr("GDN"));
		temp.insert("A2", QObject::tr("Total erase count"));
		temp.insert("A3", QObject::tr("Max PE cycle"));
		temp.insert("A4", QObject::tr("Average erase count"));
		temp.insert("A5", QObject::tr("Initial bad block count"));
		temp.insert("A6", QObject::tr("Total bad block count"));
		temp.insert("A7", QObject::tr("SSD protect mode"));
		temp.insert("A8", QObject::tr("SATA Phy error count"));
		temp.insert("A9", QObject::tr("Health"));
		temp.insert("AB", QObject::tr("Program fail count"));
		temp.insert("AC", QObject::tr("Erase fail count"));
		temp.insert("AE", QObject::tr("Unexpected power loss count"));
		temp.insert("AF", QObject::tr("ECC fail count"));
		temp.insert("B5", QObject::tr("Unaligned access count"));
		temp.insert("BB", QObject::tr("Reported uncorrectable error"));
		temp.insert("C2", QObject::tr("Enclosure temperature"));
		temp.insert("C3", QObject::tr("Cumulative corrected ecc"));
		temp.insert("C4", QObject::tr("Reallocation event count"));
		temp.insert("C7", QObject::tr("Ultra DMA CRC error count"));
		temp.insert("CE", QObject::tr("Min. erase count"));
		temp.insert("CF", QObject::tr("Max erase count"));
		temp.insert("E7", QObject::tr("Lifetime left"));
		temp.insert("E8", QObject::tr("Available reserved space"));
		temp.insert("F1", QObject::tr("Write life time"));
		temp.insert("F2", QObject::tr("Read life time"));
		temp.insert("F9", QObject::tr("Total GB written to NAND"));
		temp.insert("FA", QObject::tr("Total GB written to NAND (SLC)"));
		allInfos["SmartRealtek"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Re-Assigned Sector Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("64", QObject::tr("Total Erase Count"));
		temp.insert("A8", QObject::tr("Min. Erase Count"));
		temp.insert("A9", QObject::tr("Max. Erase Count"));
		temp.insert("AA", QObject::tr("Reserve Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("AF", QObject::tr("Program Fail Count(Worst Case)"));
		temp.insert("B0", QObject::tr("Erase Fail Count(Worst Case)"));
		temp.insert("B1", QObject::tr("Wear Leveling Count"));
		temp.insert("B2", QObject::tr("Used Reseved Block Count(Worst Case)"));
		temp.insert("B3", QObject::tr("Used Reseved Block Count(SSD Total)"));
		temp.insert("B4", QObject::tr("UnUsed Reseved Block Count(SSD Total)"));
		temp.insert("B5", QObject::tr("Program Fail Count(SSD Total)"));
		temp.insert("B6", QObject::tr("Erase Fail Count(SSD Total)"));
		temp.insert("B7", QObject::tr("SATA Downshift Count"));
		temp.insert("B8", QObject::tr("End-to-End Error Detection Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BC", QObject::tr("Command Timeout Count"));
		temp.insert("BF", QObject::tr("Op Shock Event Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("ECC Rate"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Sector Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("C9", QObject::tr("Uncorrectable Soft Read Error Rate"));
		temp.insert("CC", QObject::tr("Soft ECC Correction Rate"));
		temp.insert("D4", QObject::tr("Phy Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E9", QObject::tr("SSD Life Left"));
		temp.insert("EA", QObject::tr("NAND Written"));
		temp.insert("F1", QObject::tr("Total LBA Written"));
		temp.insert("F2", QObject::tr("Total LBA Read"));
		temp.insert("FA", QObject::tr("Total Number of NAND Read Retries"));
		allInfos["SmartSKhynix"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("09", QObject::tr("Power-On Hours Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A7", QObject::tr("SSD Protect Mode"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("A9", QObject::tr("Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase Count (User Data)"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("F1", QObject::tr("Host Writes"));
		allInfos["SmartKioxia"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A5", QObject::tr("Block Erase Count (SLC)"));
		temp.insert("A6", QObject::tr("Minimum P/E Cycles"));
		temp.insert("A7", QObject::tr("Maximum Bad Blocks per die"));
		temp.insert("A8", QObject::tr("Maximum P/E Cycles"));
		temp.insert("A9", QObject::tr("Total Bad Block"));
		temp.insert("AA", QObject::tr("Grown Bad Blocks"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average P/E Cycles"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B8", QObject::tr("End-to-End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("BC", QObject::tr("Command Timeout Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("D4", QObject::tr("SATA PHY Error"));
		temp.insert("E6", QObject::tr("Media Wearout Indicator"));
		temp.insert("E8", QObject::tr("Available Reserve Space"));
		temp.insert("E9", QObject::tr("NAND GB Written"));
		temp.insert("EA", QObject::tr("NAND GB Written (SLC)"));
		temp.insert("EE", QObject::tr("Media Wearout Indicator (Cycles Remaining)"));
		temp.insert("F1", QObject::tr("Total GB Written"));
		temp.insert("F2", QObject::tr("Total GB Read"));
		temp.insert("F3", QObject::tr("Total NAND Writes"));
		temp.insert("F4", QObject::tr("Temperature Throttle Status"));
		temp.insert("F9", QObject::tr("NAND GB Written"));
		allInfos["SmartWdc"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Sector Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Used Reserved Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Off Count"));
		temp.insert("AF", QObject::tr("Program Fail Count Worst Die"));
		temp.insert("B0", QObject::tr("Erase Fail Count Worst Die"));
		temp.insert("B1", QObject::tr("Wear Leveling Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count worst Die"));
		temp.insert("B4", QObject::tr("Unused Reserved Block Count (SSD Total)"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("On-the-Fly ECC Error Count"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Pending Sector Count"));
		temp.insert("C7", QObject::tr("UDMA CRC Error Count"));
		temp.insert("C9", QObject::tr("Uncorrectable Read Error Rate"));
		temp.insert("CC", QObject::tr("Soft ECC Correction Rate"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("EA", QObject::tr("Lifetime Nand Writes"));
		temp.insert("F1", QObject::tr("Lifetime Host Writes"));
		temp.insert("F2", QObject::tr("Lifetime Host Reads"));
		temp.insert("FA", QObject::tr("Total Number of NAND Read Retries"));
		allInfos["SmartKingstonSuv"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Re-Allocated NAND Block Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("94", QObject::tr("Reserved"));
		temp.insert("95", QObject::tr("Reserved"));
		temp.insert("96", QObject::tr("Reserved"));
		temp.insert("97", QObject::tr("SLC Average Erase Count"));
		temp.insert("9F", QObject::tr("DRAM 1 bit Error Count"));
		temp.insert("A0", QObject::tr("Reported UECC (UnCorrectable) Errors"));
		temp.insert("A1", QObject::tr("Available Reserved Space"));
		temp.insert("A4", QObject::tr("Reserved"));
		temp.insert("A5", QObject::tr("Reserved"));
		temp.insert("A6", QObject::tr("Reserved"));
		temp.insert("A7", QObject::tr("Average Erase Count"));
		temp.insert("A8", QObject::tr("Reserved"));
		temp.insert("A9", QObject::tr("Percentage Of Rated Lifetime Remaining"));
		temp.insert("B1", QObject::tr("Reserved"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Fail Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Device Temperature"));
		temp.insert("C3", QObject::tr("Hardware ECC Recovered"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C7", QObject::tr("UDMA CRC Error Count"));
		temp.insert("E7", QObject::tr("Percentage of Rated Lifetime Remaining"));
		temp.insert("E8", QObject::tr("Unused Reserved Block Count"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("F5", QObject::tr("Total Media Writes"));
		allInfos["SmartKingstonKC600"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Host UNC Error Count"));
		temp.insert("09", QObject::tr("Power on Hours"));
		temp.insert("0C", QObject::tr("Power On / Off Cycle"));
		temp.insert("A7", QObject::tr("Protect mode"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("A9", QObject::tr("Bad Block Rate"));
		temp.insert("AA", QObject::tr("Bad Block Information"));
		temp.insert("AC", QObject::tr("Erase Failure Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Failure Count"));
		temp.insert("BB", QObject::tr("Host UNC Error Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Total Later Bad Block Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("CF", QObject::tr("Thermal Throttling Count"));
		temp.insert("DA", QObject::tr("CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Remaining"));
		temp.insert("E8", QObject::tr("Read Fail Count"));
		temp.insert("E9", QObject::tr("NAND Write"));
		temp.insert("F1", QObject::tr("Host Write"));
		temp.insert("F2", QObject::tr("Host Read"));
		temp.insert("F4", QObject::tr("Avg Erase Count"));
		temp.insert("F5", QObject::tr("Max Erase Count"));
		temp.insert("F6", QObject::tr("Total Erase Count"));
		allInfos["SmartKingstonDC500"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Uncorrectable Errors"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycles"));
		temp.insert("94", QObject::tr("Vendor Unique"));
		temp.insert("95", QObject::tr("Vendor Unique"));
		temp.insert("A7", QObject::tr("Vendor Unique"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("A9", QObject::tr("Vendor Unique"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AC", QObject::tr("Vendor Unique"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("B5", QObject::tr("Vendor Unique"));
		temp.insert("B6", QObject::tr("Vendor Unique"));
		temp.insert("BB", QObject::tr("Uncorrectable ECC Errors"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocation Events"));
		temp.insert("C7", QObject::tr("SATA CRC Error"));
		temp.insert("DA", QObject::tr("CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Wear Indicator"));
		temp.insert("E9", QObject::tr("Lifetime Nand Writes"));
		temp.insert("F1", QObject::tr("Lifetime Writes from Host"));
		temp.insert("F2", QObject::tr("Lifetime Read from Host"));
		temp.insert("F4", QObject::tr("Average Erase Count"));
		temp.insert("F5", QObject::tr("Max Erase Count"));
		temp.insert("F6", QObject::tr("Total Erase Count"));
		allInfos["SmartKingstonSA400"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Available Reserved Space"));
		temp.insert("AB", QObject::tr("Program Fail Count (Total)"));
		temp.insert("AC", QObject::tr("Erase Fail Count (Total)"));
		temp.insert("AD", QObject::tr("Average Program/Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("AF", QObject::tr("Program Fail count (Worst case)"));
		temp.insert("B0", QObject::tr("Erase Fail Count (Worst case)"));
		temp.insert("B1", QObject::tr("Wear Leveling Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count (Worst case)"));
		temp.insert("B3", QObject::tr("Used Reserved Block Count (Total)"));
		temp.insert("B4", QObject::tr("Unused Reserved Block Count (Total)"));
		temp.insert("B7", QObject::tr("SATA Interface Down shift"));
		temp.insert("B8", QObject::tr("End-to-End Data Errors Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BC", QObject::tr("Command Time out"));
		temp.insert("C2", QObject::tr("Drive Temperature"));
		temp.insert("C3", QObject::tr("ECC rate"));
		temp.insert("C6", QObject::tr("OffLine Uncorrectable Error Count"));
		temp.insert("C7", QObject::tr("SATA CRC Error Count"));
		temp.insert("E5", QObject::tr("Power Loss Protection Failure"));
		temp.insert("E7", QObject::tr("Percentage Lifetime Remaining"));
		temp.insert("E8", QObject::tr("Available Reserved Space "));
		temp.insert("E9", QObject::tr("NAND GB Written"));
		temp.insert("F1", QObject::tr("Total Host Write"));
		temp.insert("F2", QObject::tr("Total Host Read "));
		temp.insert("F3", QObject::tr("NAND GB Written"));
		allInfos["SmartSsstc"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Count"));
		temp.insert("05", QObject::tr("Reallocated Flash Block Count"));
		temp.insert("09", QObject::tr("Power-On Hours Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("0E", QObject::tr("Device Capacity"));
		temp.insert("0F", QObject::tr("User Capacity"));
		temp.insert("10", QObject::tr("Spare Blocks Available"));
		temp.insert("11", QObject::tr("Remaining Spare Available"));
		temp.insert("AC", QObject::tr("Total Block Erase Failure"));
		temp.insert("AD", QObject::tr("Per Block Max Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("AF", QObject::tr("Average Erase Count"));
		temp.insert("B0", QObject::tr("Power Loss Protection Error"));
		temp.insert("B5", QObject::tr("Total Block Program Failure"));
		temp.insert("B8", QObject::tr("End-to-End Error Detection Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C5", QObject::tr("Pending Sector Count"));
		temp.insert("C6", QObject::tr("Offline Uncorrectable Error Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("CA", QObject::tr("Percentage of Drive Life Used"));
		temp.insert("E2", QObject::tr("Timed Workload - Media Wear"));
		temp.insert("E3", QObject::tr("Timed Workload - Host Read/Write Ratio"));
		temp.insert("E4", QObject::tr("Timed Workload Timer"));
		temp.insert("EA", QObject::tr("Thermal Throttle Status"));
		temp.insert("EB", QObject::tr("Total Host Bytes/Sectors Written"));
		temp.insert("F1", QObject::tr("Total Nand Bytes/Sectors Written"));
		allInfos["SmartIntelDc"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("09", QObject::tr("Power on Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A3", QObject::tr("Maximum Erase Count"));
		temp.insert("A4", QObject::tr("Average Erase Count"));
		temp.insert("A6", QObject::tr("Total Later Bad Block Count"));
		temp.insert("A7", QObject::tr("SSD Protect Mode"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AF", QObject::tr("Bad Cluster Table Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("E7", QObject::tr("Lifetime Left"));
		temp.insert("F1", QObject::tr("Total Sectors Write"));
		allInfos["SmartApacer"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("94", QObject::tr("SLC Total Erase Count"));
		temp.insert("95", QObject::tr("SLC Maximum Erase Count"));
		temp.insert("96", QObject::tr("SLC Minimum Erase Count"));
		temp.insert("97", QObject::tr("SLC Average Erase Count"));
		temp.insert("9F", QObject::tr("DRAM 1 bit Error Count"));
		temp.insert("A0", QObject::tr("Uncorrectable sectors count when read/write"));
		temp.insert("A1", QObject::tr("Number of Valid Spare Blocks"));
		temp.insert("A2", QObject::tr("Number of Cache Data Block"));
		temp.insert("A3", QObject::tr("Number of Initial Invalid Blocks"));
		temp.insert("A4", QObject::tr("Total Erase Count"));
		temp.insert("A5", QObject::tr("Maximum Erase Count"));
		temp.insert("A6", QObject::tr("Minimum Erase Count"));
		temp.insert("A7", QObject::tr("Average Erase Count"));
		temp.insert("A8", QObject::tr("Max Erase Count of Spec"));
		temp.insert("A9", QObject::tr("Remain Life"));
		temp.insert("AF", QObject::tr("Program fail count in worst die"));
		temp.insert("B0", QObject::tr("Erase fail count in worst die"));
		temp.insert("B1", QObject::tr("Total Wear Level Count"));
		temp.insert("B2", QObject::tr("Runtime Invalid Block Count"));
		temp.insert("B5", QObject::tr("Total Program Fail Count"));
		temp.insert("B6", QObject::tr("Total Erase Fail Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("C0", QObject::tr("Power-Off Retract Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("Hardware ECC Recovered"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Error Count Off-line"));
		temp.insert("C7", QObject::tr("Ultra DMA CRC Error Count"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("F1", QObject::tr("Total LBA Written"));
		temp.insert("F2", QObject::tr("Total LBA Read"));
		temp.insert("F5", QObject::tr("Flash Write Sector Count"));
		allInfos["SmartSiliconMotion"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("02", QObject::tr("Throughput Performance"));
		temp.insert("03", QObject::tr("Spin-Up Time"));
		temp.insert("05", QObject::tr("Reallocated Sectors Count"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("08", QObject::tr("Seek Time Performance"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0A", QObject::tr("Spin Retry Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A7", QObject::tr("SSD Protect Mode"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("AF", QObject::tr("Bad Cluster Table Count"));
		temp.insert("B4", QObject::tr("Spare Block Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C5", QObject::tr("Current Pending Sector Count"));
		temp.insert("E7", QObject::tr("Drive Life"));
		temp.insert("E9", QObject::tr("Write Sector Count (NAND)"));
		temp.insert("F0", QObject::tr("Write Head"));
		temp.insert("F1", QObject::tr("Total LBA Written"));
		temp.insert("F2", QObject::tr("Total LBA Read"));
		allInfos["SmartJMicron66x"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("09", QObject::tr("Power on Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("DA", QObject::tr("Number of CRC Error"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("F1", QObject::tr("Host Writes"));
		allInfos["SmartPhison"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Read Error Rate"));
		temp.insert("05", QObject::tr("Retired Sectors Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("10", QObject::tr("Spare Blocks Available"));
		temp.insert("11", QObject::tr("Remaining Spare Blocks"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B1", QObject::tr("Wear Range Delta"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Fail Count"));
		temp.insert("C0", QObject::tr("Unexpected Power loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C9", QObject::tr("Soft Error Rate"));
		temp.insert("CC", QObject::tr("Soft ECC Correction Rate"));
		temp.insert("DA", QObject::tr("CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E8", QObject::tr("Read Failure Block Count"));
		temp.insert("E9", QObject::tr("NAND GiB Written"));
		temp.insert("EA", QObject::tr("Lifetime Writes To Flash"));
		temp.insert("EB", QObject::tr("NAND sectors Written"));
		temp.insert("F1", QObject::tr("Lifetime Writes From Host"));
		temp.insert("F2", QObject::tr("Lifetime Reads From Host"));
		temp.insert("FA", QObject::tr("Lifetime NAND Read Retries"));
		allInfos["SmartSeagate"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Sector Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("64", QObject::tr("Flash Gigabytes Erased"));
		temp.insert("66", QObject::tr("Lifetime PS4 Entry Count"));
		temp.insert("67", QObject::tr("Lifetime PS3 Entry Count"));
		temp.insert("AA", QObject::tr("Grown Bad Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average Program/Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B1", QObject::tr("Wear Range Delta"));
		temp.insert("B7", QObject::tr("SATA/PCIe Interface Downshift Count"));
		temp.insert("BB", QObject::tr("Uncorrectable ECC Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("RAISE ECC Correctable Count"));
		temp.insert("C6", QObject::tr("Uncorrectable Read Error Count"));
		temp.insert("C7", QObject::tr("SATA R-Error (CRC) Error Count"));
		temp.insert("E6", QObject::tr("Drive Life Protection Status"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("E9", QObject::tr("Lifetime Writes to Flash"));
		temp.insert("F1", QObject::tr("Lifetime Writes From Host"));
		temp.insert("F2", QObject::tr("Lifetime Reads From Host"));
		temp.insert("F3", QObject::tr("Free Space"));
		allInfos["SmartSeagateIronWolf"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Number of New Bad Block"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A4", QObject::tr("Total Erase Count"));
		temp.insert("A5", QObject::tr("Maximum Erase Count"));
		temp.insert("A6", QObject::tr("Minimum Erase Count"));
		temp.insert("A7", QObject::tr("Average Erase Count"));
		temp.insert("C0", QObject::tr("Power off Retract Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C7", QObject::tr("SATA CRC Error Count"));
		temp.insert("F1", QObject::tr("Total Written"));
		temp.insert("F2", QObject::tr("Total Read"));
		allInfos["SmartMarvell"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Reallocated Sector Count"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("A7", QObject::tr("SSD Protect Mode"));
		temp.insert("A8", QObject::tr("PHY Error Count"));
		temp.insert("A9", QObject::tr("Bad Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("AF", QObject::tr("Bad Cluster Table Count"));
		temp.insert("B1", QObject::tr("Read Retry Count"));
		temp.insert("B4", QObject::tr("Spare Block Count Left"));
		temp.insert("BB", QObject::tr("Reported UNC Errors"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocated Event Count"));
		temp.insert("C7", QObject::tr("UDMA CRC Error Count"));
		temp.insert("CE", QObject::tr("Minimum Erase Count"));
		temp.insert("CF", QObject::tr("Maximum Erase Count"));
		temp.insert("D0", QObject::tr("Average Erase Count"));
		temp.insert("D1", QObject::tr("Minimum Erase Count of SLC block"));
		temp.insert("D2", QObject::tr("Maximum Erase Count of SLC block"));
		temp.insert("D3", QObject::tr("Average Erase Count of SLC block"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E9", QObject::tr("Write Counts Sectors to Nand"));
		temp.insert("EA", QObject::tr("Read Counts Sectors from Nand"));
		temp.insert("F1", QObject::tr("Write Sector Count"));
		temp.insert("F2", QObject::tr("Read Sector Count"));
		temp.insert("F5", QObject::tr("Bit Error Count"));
		allInfos["SmartMaxiotek"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("UECC Error Count"));
		temp.insert("05", QObject::tr("Retired Sectors Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("10", QObject::tr("Spare Blocks Available"));
		temp.insert("11", QObject::tr("Remaining Spare Blocks"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("AA", QObject::tr("Bad Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B1", QObject::tr("Wear Range Delta"));
		temp.insert("B5", QObject::tr("Program Fail Count"));
		temp.insert("B6", QObject::tr("Erase Fail Count"));
		temp.insert("C0", QObject::tr("Unexpected Power loss Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C9", QObject::tr("Soft Error Rate"));
		temp.insert("CC", QObject::tr("Soft ECC Correction Rate"));
		temp.insert("DA", QObject::tr("CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E8", QObject::tr("Read Failure Block Count"));
		temp.insert("E9", QObject::tr("NAND GiB Written"));
		temp.insert("EA", QObject::tr("Lifetime Writes To Flash"));
		temp.insert("EB", QObject::tr("NAND sectors Written"));
		temp.insert("F1", QObject::tr("Lifetime Writes From Host"));
		temp.insert("F2", QObject::tr("Lifetime Reads From Host"));
		temp.insert("FA", QObject::tr("Lifetime NAND Read Retries"));
		allInfos["SmartSeagateBarraCuda"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("New Bad Block Count"));
		temp.insert("09", QObject::tr("Power-On Hours Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AA", QObject::tr("Max Bad Block Count"));
		temp.insert("A8", QObject::tr("SATA PHY Error Count"));
		temp.insert("A9", QObject::tr("Bad Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("AF", QObject::tr("Bad Cluster Count"));
		temp.insert("B7", QObject::tr("SATA Interface Downshift"));
		temp.insert("B8", QObject::tr("End to End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BE", QObject::tr("Temperature"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C4", QObject::tr("Re-allocated Event Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("CE", QObject::tr("Minimum Erase Count"));
		temp.insert("CF", QObject::tr("Maximum Erase Count"));
		temp.insert("D0", QObject::tr("Average Erase Count"));
		temp.insert("D1", QObject::tr("SLC Minimum Erase Count"));
		temp.insert("D2", QObject::tr("SLC Maximum Erase Count"));
		temp.insert("D3", QObject::tr("SLC Average Erase Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("E9", QObject::tr("Write sector count to NAND"));
		temp.insert("EA", QObject::tr("Read sector count to NAND"));
		temp.insert("F1", QObject::tr("Total LBA written"));
		temp.insert("F2", QObject::tr("Total LBA Read"));
		temp.insert("F3", QObject::tr("NAND Temperature"));
		temp.insert("F5", QObject::tr("Bit Error Count"));
		allInfos["SmartYmtc"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated Sector Count"));
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("A7", QObject::tr("Average Erase Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("B1", QObject::tr("Read Retry Count"));
		temp.insert("B4", QObject::tr("Spare Block Count Left"));
		temp.insert("B7", QObject::tr("Runtime Bad Block"));
		temp.insert("BB", QObject::tr("Reported UNC Errors"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Controlled Temperature"));
		temp.insert("C3", QObject::tr("Cumulative ECC Bit Correction Count"));
		temp.insert("C4", QObject::tr("Reallocated Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector"));
		temp.insert("C7", QObject::tr("UDMA CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("F5", QObject::tr("Total Nand Flash Written"));
		allInfos["SmartScy"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("07", QObject::tr("Seek Error Rate"));
		temp.insert("09", QObject::tr("Power-On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("A7", QObject::tr("Average erase count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Erase Count"));
		temp.insert("B1", QObject::tr("Read Retry Count"));
		temp.insert("B4", QObject::tr("Spare Block Count Left"));
		temp.insert("B7", QObject::tr("Runtime Bad Block"));
		temp.insert("BB", QObject::tr("Reported UNC Errors"));
		temp.insert("C0", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("C2", QObject::tr("Controlled temperature"));
		temp.insert("C3", QObject::tr("Cumulative ECC Bit Correction Count"));
		temp.insert("C4", QObject::tr("Reallocated Event Count"));
		temp.insert("C5", QObject::tr("Current Pending Sector"));
		temp.insert("C7", QObject::tr("UDMA CRC Error Count"));
		temp.insert("E7", QObject::tr("SSD Life Left"));
		temp.insert("F1", QObject::tr("Total LBAs written"));
		temp.insert("F2", QObject::tr("Total LBAs read"));
		temp.insert("F5", QObject::tr("Total Nand Flash Written"));
		allInfos["SmartRecadata"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("AA", QObject::tr("Reserved Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Wear Leveling Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B0", QObject::tr("Unused Reserved Block Count"));
		temp.insert("B7", QObject::tr("SATA Interface Downshift Count"));
		temp.insert("B8", QObject::tr("End to End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BC", QObject::tr("Command Time Out"));
		temp.insert("BE", QObject::tr("Airflow Temperature"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocated Event Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("C9", QObject::tr("SSD Life Left"));
		temp.insert("E6", QObject::tr("Media Wearout Indicator"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("F3", QObject::tr("Throttle Statistics"));
		temp.insert("F4", QObject::tr("Temperature Throttle Status"));
		temp.insert("F9", QObject::tr("TLC NAND GB Writes"));
		allInfos["SmartSanDiskHp"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("AA", QObject::tr("Reserved Block Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Wear Leveling Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B0", QObject::tr("Unused Reserved Block Count"));
		temp.insert("B7", QObject::tr("SATA Interface Downshift Count"));
		temp.insert("B8", QObject::tr("End to End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("BC", QObject::tr("Command Time Out"));
		temp.insert("BE", QObject::tr("Airflow Temperature"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocated Event Count"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("C9", QObject::tr("SSD Life Left"));
		temp.insert("E6", QObject::tr("Media Wearout Indicator"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("F3", QObject::tr("Total NAND Writes"));
		temp.insert("F4", QObject::tr("Temperature Throttle Status"));
		temp.insert("F9", QObject::tr("TLC NAND GB Writes"));
		allInfos["SmartSanDiskHpVenus"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("AF", QObject::tr("Program Fail Count (Worst Case Component)"));
		temp.insert("B0", QObject::tr("Erase Fail Count (Worst Case Component)"));
		temp.insert("B1", QObject::tr("Wear Leveling Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count (Worst Case Component)"));
		temp.insert("B3", QObject::tr("Used Reserved Block Count (SSD Total)"));
		temp.insert("B4", QObject::tr("Remaining Reserved Block Count (SSD Total)"));
		temp.insert("B5", QObject::tr("Program Fail Count (SSD Total)"));
		temp.insert("B6", QObject::tr("Erase Fail Count (SSD Total)"));
		temp.insert("BB", QObject::tr("Uncorrectable Error Count"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C3", QObject::tr("ECC Rate"));
		temp.insert("C7", QObject::tr("CRC Error Count"));
		temp.insert("E6", QObject::tr("Media Wearout Indicator"));
		temp.insert("EE", QObject::tr("Media Wearout Indicator (Cycles Remaining)"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		allInfos["SmartSanDiskDell"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("A6", QObject::tr("Minimum P/E Cycles"));
		temp.insert("A7", QObject::tr("Maximum Bad Blocks per Die"));
		temp.insert("A8", QObject::tr("Maximum P/E cycles"));
		temp.insert("A9", QObject::tr("Total Bad Blocks"));
		temp.insert("AA", QObject::tr("Grown Bad Blocks"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average P/E Cycles Attribute"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count"));
		temp.insert("B4", QObject::tr("Remaining Reserved Block Count"));
		temp.insert("B8", QObject::tr("End to End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("UECC Count"));
		temp.insert("BC", QObject::tr("Command Time Out"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C7", QObject::tr("SATA CRC Errors"));
		temp.insert("D4", QObject::tr("SATA PHY Errors"));
		temp.insert("E6", QObject::tr("Media Wearout Indicator"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("E9", QObject::tr("NAND GB Written"));
		temp.insert("EA", QObject::tr("NAND GB Written (SLC)"));
		temp.insert("F1", QObject::tr("Total Host GB Write"));
		temp.insert("F2", QObject::tr("Total GB Read"));
		temp.insert("F3", QObject::tr("Throttle Statistics"));
		temp.insert("F4", QObject::tr("Thermal Throttle Status"));
		allInfos["SmartSanDiskLenovo"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("05", QObject::tr("Reassigned Block Count"));
		temp.insert("09", QObject::tr("Power On Hours"));
		temp.insert("0C", QObject::tr("Drive Power Cycle Count"));
		temp.insert("A6", QObject::tr("Minimum P/E Cycles"));
		temp.insert("A7", QObject::tr("Maximum Bad Blocks per Die"));
		temp.insert("A8", QObject::tr("Maximum P/E cycles"));
		temp.insert("A9", QObject::tr("Total Bad Blocks"));
		temp.insert("AA", QObject::tr("Grown Bad Blocks"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average P/E Cycles Attribute"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B2", QObject::tr("Used Reserved Block Count"));
		temp.insert("B4", QObject::tr("Remaining Reserved Block Count"));
		temp.insert("B8", QObject::tr("End to End Error Detection/Correction Count"));
		temp.insert("BB", QObject::tr("UECC Count"));
		temp.insert("BC", QObject::tr("Command Time Out"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C7", QObject::tr("SATA CRC Errors"));
		temp.insert("D4", QObject::tr("SATA PHY Errors"));
		temp.insert("E8", QObject::tr("Available Reserved Space"));
		temp.insert("E9", QObject::tr("Media Wearout Indicator"));
		temp.insert("EA", QObject::tr("NAND GB Written (SLC)"));
		temp.insert("F1", QObject::tr("Total Host GB Write"));
		temp.insert("F2", QObject::tr("Total GB Read"));
		temp.insert("F3", QObject::tr("Throttle Statistics"));
		temp.insert("F4", QObject::tr("Thermal Throttle Status"));
		temp.insert("F9", QObject::tr("NAND GB Written (TLC)"));
		allInfos["SmartSanDiskLenovoHelenVenus"] = temp;
	}
	{
		QMap<QString, QString> temp;
		temp.insert("01", QObject::tr("Raw Read Error Rate"));
		temp.insert("05", QObject::tr("Reallocated NAND Block Count"));
		temp.insert("09", QObject::tr("Power On Hours Count"));
		temp.insert("0C", QObject::tr("Power Cycle Count"));
		temp.insert("AB", QObject::tr("Program Fail Count"));
		temp.insert("AC", QObject::tr("Erase Fail Count"));
		temp.insert("AD", QObject::tr("Average Block Erase Count"));
		temp.insert("AE", QObject::tr("Unexpected Power Loss Count"));
		temp.insert("B4", QObject::tr("Unused Spare NAND Blocks"));
		temp.insert("B5", QObject::tr("Non-4K Aligned Access"));
		temp.insert("B7", QObject::tr("SATA interface Downshift"));
		temp.insert("B8", QObject::tr("Error Correction Count"));
		temp.insert("BB", QObject::tr("Reported Uncorrectable Errors"));
		temp.insert("C2", QObject::tr("Temperature"));
		temp.insert("C4", QObject::tr("Reallocation Event Count"));
		temp.insert("C5", QObject::tr("Current Pending ECC Count"));
		temp.insert("C6", QObject::tr("SMART Offline Scan Uncorrectable Error Count"));
		temp.insert("C7", QObject::tr("UDMA CRC Error Count"));
		temp.insert("CA", QObject::tr("Lifetime Remaining"));
		temp.insert("CE", QObject::tr("Write Error Rate"));
		temp.insert("D2", QObject::tr("Successful RAIN Recovery Count"));
		temp.insert("F0", QObject::tr("Host Program Page Count"));
		temp.insert("F1", QObject::tr("Total LBAs Written"));
		temp.insert("F2", QObject::tr("Total LBAs Read"));
		temp.insert("F3", QObject::tr("Total Program Page Count"));
		temp.insert("F6", QObject::tr("Cumulative Host Sectors Written"));
		temp.insert("F7", QObject::tr("Host Program NAND Pages Count"));
		temp.insert("F8", QObject::tr("FTL Program NAND Pages Count"));
		allInfos["SmartMicronMU03"] = temp;
	}

	return allInfos;
}